logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
      springframework:
        security: ERROR
        web: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/octet-stream
          destination: csdip
        output:
          contentType: application/octet-stream
          destination: csdip
      kafka:
        binder:
          brokers: localhost:9092
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true
